title:              "Loading Blog"
tagline:            "국내 바이럴 광고 및 공식 광고"
email:              "ndk0929@gmail.com"
description:        "광고업에서 경험한 주관적인 경험담"
author:             "Loading"
baseurl:            "/"
url:                "https://loading.kr"
locale:             "ko_KR"
thumbnail:          "/img/smain.png"

# Social Profiles
instagram_username: nohdk777
facebook_username:  100010201817907
linkedin_username:  동규-노-478872155

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
# 블로그 disqus shortname
disqus:
  shortname: loading-kr
